#!/bin/bash
BASEDIR=$(dirname "$0")
rmdir ./out 
mkdir ./out
mvn clean package -DskipTests -f ../../
java -jar ${BASEDIR}/target/compilers-1.0-SNAPSHOT-jar-with-dependencies.jar "$1" "$2"
if [ "$1" == "-o" ]; then
    ${BASEDIR}/compile.sh "$2"
fi
